function [] = run_spinodal_decomp_FD()
    in_file = "/home/xpz5km/Cahn_Hilliard_Model/spinodal_decomp/IC/initial_phi_128_smooth_n_relax_4.csv";
    outdir="/project/g_bme-janeslab/SarahG/spinodal_decomp_04_2025/out_MATLAB/FD"

    m = 8;
    GridSize = 128;
    % dt = .9e-2/(GridSize^2);
    dt = 5.5e-8;
    n_relax = 4;
    h = 1/GridSize;
    epsilon = m * (1 / 128) / (2 * sqrt(2) * atanh(0.9));
    % epsilon = m/(2 * sqrt(2) * atanh(0.9));
    gamma = epsilon^2/h^2;
    D = GridSize^2;
    total_time = dt*200000;
    max_it = round(total_time / dt);
    FileName = sprintf("%s/FD_%d_dt_%.2e_Nx_%d_n_relax_%d_gam_%.2e_D_%g_update",outdir,max_it,dt, GridSize,n_relax, gamma,D);
    dt_out = 100;

    % max_it = 4000;
    % GridSize = 128;
    tStart = tic;

    [phi_t,mass_t,E_t] = spinodal_decomp(D,gamma, ...
                    "dt",dt,...
                    "GridSize",GridSize,...
                    "CaptureMode","standard",...
                    "NumIterations",max_it,...
                    "FrameSpacing",dt_out,...
                    "ns",dt_out,...
                    'ImgStyle','true',...
                    "InputMatrix",in_file,...
                    "FileName",FileName,...
                    "InputType",'phi',...
                    "ConstantColorbar", true,...
                    "write_residual",false,...
                    "write_phi",true,...
                    "frame_per_sec",false);
    elapsedTime = toc(tStart)
    %writematrix(final_phi,sprintf('%s_final_phi.csv', FileName));
    writematrix(mass_t,sprintf('%s_mass.csv', FileName));
    writematrix(E_t,sprintf('%s_energy.csv', FileName));
end
